name: rag-api-project

services:
  app:
    container_name: rag-app
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434

    depends_on:
      - ollama

  frontend:
    container_name: rag-frontend
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Uncomment the lines below to enable GPU support (requires NVIDIA Container Toolkit)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
